version: "3.7"

services:

  frontend-react:
    build: ./frontend-react
    container_name: frontend-react
    restart: always
    volumes:
      - 'myshare:/shared'

  backend-node-express:
    build: ./backend-node-express
    container_name: backend_node_express
    ports:
      - "8000:8000"  # open this so we can use create react app development
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://my_redis
      - PORT=8000
    command:
      sh -c 'npm i && node index.js'

  nginx-react:
    build: ./nginx
    container_name: nginx-react
    restart: always
    ports:
      - "80:80"
    volumes:
      - 'myshare:/shared'

  redis:
    image: redis
    container_name: my_redis
    expose:
      - 6379

volumes:
    myshare:
      driver: local
